import ase

def atoms(calc, val):
    """The Atoms object"""
    assert isinstance(val, ase.Atoms)


def calculation(calc, val):
    """"""
    assert isinstance(val, str)

    values = ['scf', 'nscf', 'bands', 'relax', 'md', 'vc-relax', 'vc-md']
    assert val in values


def prefix(calc, val):
    """"""
    assert isinstance(val, str)


def outdir(calc, val):
    """"""
    assert isinstance(val, str)


VARIABLES = {
    # CONTROL
    'calculation': 'scf',
    'title': '',
    'verbosity': 'low',
    'restart_mode': 'from_scratch',
    'wf_collect': True,
    'nstep': 1,
    'iprint': None,
    'tstress': False,
    'tprnfor': True,
    'dt': None,
    'outdir': '.',
    'wfcdir': None,
    'prefix': 'calc',
    'lkpoint_dir': True,
    'max_seconds': None,
    'etot_conv_thr': 1e-4,
    'forc_conv_thr': 1e-3,
    'disk_io': 'low',
    'pseudo_dir': None,
    'tefield': False,
    'dipfield': False,
    'lelfield': False,
    'nberrycyc': 1,
    'lorbm': False,
    'lberry': False,
    'gdir': None,
    'nppstr': None,
    'lfcpopt': False,
    'gate': False,
    # SYSTEM
    'ibrav': 0,
    'celldm': None,
    'A': None,
    'B': None,
    'C': None,
    'cosAB': None,
    'cosAC': None,
    'cosBC': None,
    'nat': None,
    'ntyp': None,
    'nbnd': None,
    'tot_charge': 0.0,
    'starting_charge': None,
    'tot_magnetization': -1,
    'starting_magnetization': None,
    'ecutwfc': None,
    'ecutrho': None,
    'ecutfock': None,
    'nr1': None,
    'nr2': None,
    'nr3': None,
    'nr1s': None,
    'nr2s': None,
    'nr3s': None,
    'nosym': False,
    'nosym_evc': False,
    'noinv': False,
    'no_t_rev': False,
    'force_symmorphic': False,
    'use_all_frac': False,
    'occupations': 'smearing',
    'one_atom_occupations': False,
    'starting_spin_angle': False,
    'degauss': 0,
    'smearing': 'gaussian',
    'nspin': 1,
    'noncolin': False,
    'ecfixed': 0,
    'qcutz': 0,
    'q2sigma': 0.1,
    'input_dft': None,
    'exx_fraction': None,
    'screening_parameter': 0.106,
    'exxdiv_treatment': 'gygi-baldereschi',
    'x_gamma_extrapolation': True,
    'ecutvcut': 0,
    'nqx1': None,
    'nqx2': None,
    'nqx3': None,
    'lda_plus_u': False,
    'lda_plus_u_kind': 0,
    'Hubbard_U': 0,
    'Hubbard_J0': None,
    'Hubbard_alpha': None,
    'Hubbard_beta': None,
    'Hubbard_J': None,
    'starting_ns_eigenvalue': None,
    'U_projection_type': 'atomic',
    'edir': 3,
    'emaxpos': 0.5,
    'eopreg': 0.1,
    'eamp': 1e-3,
    'angle1': None,
    'angle2': None,
    'constrained_magnetization': 'none',
    'fixed_magnetization': 0,
    'lambda': 1,
    'report': 100,
    'lspinorb': None,
    'assume_isolated': 'none',
    'esm_bc': 'pbc',
    'esm_w': 0,
    'esm_efield': 0,
    'esm_nfit': 4,
    'fcp_mu': 0,
    'vdw_corr': 'none',
    'london': False,
    'london_s6': 0.75,
    'london_c6': None,
    'london_rvdw': None,
    'london_rcut': 200,
    'ts_vdw_econv_thr': 1e-6,
    'ts_vdw_isolated': False,
    'xdm': False,
    'xdm_a1': 0.6836,
    'xdm_a2': 1.5045,
    'space_group': 0,
    'uniqueb': False,
    'origin_choice': 1,
    'rhombohedral': True,
    'zgate': 0.5,
    'realxz': False,
    'block': False,
    'block_1': 0.45,
    'block_2': 0.55,
    'block_height': 0.1,
    # ELECTRONS
    'electron_maxstep': 100,
    'scf_must_converge': True,
    'conv_thr': 1e-6,
    'adaptive_thr': False,
    'conv_thr_init': 1e-3,
    'conv_thr_multi': 1e-1,
    'mixing_mode': 'plain',
    'mixing_beta': 0.7,
    'mixing_ndim': 8,
    'mixing_fixed_ns': 0,
    'diagonalization': 'david',
    'ortho_para': None,  # OBSOLETE
    'diago_thr_init': None,
    'diago_cg_maxiter': None,
    'diago_david_ndim': 4,
    'diago_full_acc': False,
    'efield': 0,
    'efield_cart': (0, 0, 0),
    'efield_phase': 'none',
    'startingpot': 'atomic',
    'startingwfc': 'atomic+random',
    'tqr': False,
    # IONS
    'ion_dynamics': None,
    'ion_positions': 'default',
    'pot_extrapolation': 'atomic',
    'wfc_extrapolation': 'none',
    'remove_rigid_rot': False,
    'ion_temperature': 'not_controlled',
    'tempw': 300,
    'tolp': 100,
    'delta_t': 1,
    'nraise': 1,
    'refold_pos': False,
    'upscale': 100,
    'bfgs_ndim': 1,
    'trust_radius_max': 0.8,
    'trust_radius_min': 1e-3,
    'trust_radius_ini': 0.5,
    'w_1': 1e-2,
    'w_2': 0.5,
    # CELL
    'cell_dynamics': None,
    'press': 0,
    'wmass': None,
    'cell_factor': 1,xs
    'press_conv_thr': 0.5,
    'cell_dofree': 'all',
}
